apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventstore-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: eventstore
  template:
    metadata:
      labels:
        component: eventstore
    spec:
      containers:
        - name: eventstore
          image: reactivetradercloud/eventstore:v1.3.2-453-g07902e79
          ports:
            - containerPort: 1113
            - containerPort: 2113
