apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: pricing
  template:
    metadata:
      labels:
        component: pricing
    spec:
      containers:
        - name: pricing
          image: reactivetradercloud/servers:v1.3.2-453-g07902e79
          env:
            - name: BROKER_HOST
              value: broker
            - name: BROKER_PORT
              value: '8000'
            - name: EVENTSTORE_HOST
              value: eventstore
            - name: EVENTSTORE_PORT
              value: '1113'
          command:
            ['sh', '-c', 'tail -f /dev/null']
            # [
            #   'sh',
            #   '-c',
            #   'dotnet ./Adaptive.ReactiveTrader.Server.Pricing.dll config.prod.json',
            # ]
