apiVersion: apps/v1
kind: Deployment
metadata:
  name: blotter
  namespace: traderduty
spec:
  replicas: 1
  selector:
    matchLabels:
      component: blotter
  template:
    metadata:
      labels:
        component: blotter
    spec:
      containers:
        - name: blotter
          image: giran/servers:1.0.0
          env:
            - name: BROKER_HOST
              value: broker
            - name: BROKER_PORT
              value: '8000'
            - name: EVENTSTORE_HOST
              value: eventstore
            - name: EVENTSTORE_PORT
              value: '1113'
          command:
            [
              'sh',
              '-c',
              'dotnet ./Adaptive.ReactiveTrader.Server.Blotter.dll config.prod.json',
            ]
      initContainers:
        - name: init-broker
          image: busybox
          command: ['sh', '-c', 'until nslookup broker; do echo waiting for broker; sleep 2; done;']
        - name: init-eventstore
          image: busybox
          command: ['sh', '-c', 'until nslookup eventstore; do echo waiting for eventstore; sleep 2; done;']