apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp
  namespace: traderduty
spec:
  replicas: 1
  selector:
    matchLabels:
      component: nlp
  template:
    metadata:
      labels:
        component: nlp
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: nlp-key
      containers:
        - name: nlp
          image: giran/nlp:1.0.0
          # volumeMounts:
          #   - name: google-cloud-key
          #     mountPath: /var/secrets/google
          env:
            - name: BROKER_HOST
              value: broker
            - name: BROKER_PORT
              value: '8000'
            # - name: GOOGLE_APPLICATION_CREDENTIALS
            #   value: /var/secrets/google/key.json
      initContainers:
        - name: init-broker
          image: busybox
          command: ['sh', '-c', 'until nslookup broker; do echo waiting for broker; sleep 2; done;']
        - name: init-eventstore
          image: busybox
          command: ['sh', '-c', 'until nslookup eventstore; do echo waiting for eventstore; sleep 2; done;']