apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricehistory
  namespace: traderduty
spec:
  replicas: 1
  selector:
    matchLabels:
      component: pricehistory
  template:
    metadata:
      labels:
        component: pricehistory
    spec:
      containers:
        - name: pricehistory
          image: giran/pricehistory:1.0.0
          env:
            - name: BROKER_HOST
              value: broker
            - name: BROKER_PORT
              value: '8000'
      initContainers:
        - name: init-broker
          image: busybox
          command: ['sh', '-c', 'until nslookup broker; do echo waiting for broker; sleep 2; done;']
        - name: init-eventstore
          image: busybox
          command: ['sh', '-c', 'until nslookup eventstore; do echo waiting for eventstore; sleep 2; done;']
