apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web
          image: giran/nginx:1.0.0
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    public: 'true'
spec:
  selector:
    component: web
  ports:
    - name: web
      port: 80
      targetPort: 80
