apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: traderduty
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: web
          image: giran/nginx:1.0.0
          ports:
            - containerPort: 3000
      initContainers:
        - name: init-client
          image: busybox
          command: ['sh', '-c', 'until nslookup client; do echo waiting for client; sleep 2; done;']

---

apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: traderduty
  labels:
    name: web
    public: 'true'
spec:
  selector:
    component: web
  ports:
    - name: web
      port: 80
      targetPort: 80
